kind: Deployment
apiVersion: apps/v1
metadata:
  name: moviecollectionclient
  namespace: trip
  labels:
    app: moviecollectionclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moviecollectionclient
  template:
    metadata:
       labels:
         app: moviecollectionclient
    spec:
      containers:
        - name: moviecollectionclient
          image: moria.middle.earth:443/trip/moviecollectionclient:0.1
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
               - ALL
          env:
            - name: TARGET
              valueFrom:
                configMapKeyRef:
                  name: moviecollectionclient
                  key: TARGET
